# Generated by Django 2.2.1 on 2019-08-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('superpower', models.CharField(max_length=400)),
                ('hero_tier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Villains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('superpower', models.CharField(max_length=400)),
                ('threat_level', models.IntegerField()),
                ('nemesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superhumans.Heroes')),
            ],
        ),
        migrations.AddField(
            model_name='heroes',
            name='nemesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superhumans.Villains'),
        ),
    ]
